### ISSUE TITLE
Bug in checking accuracy

### ISSUE THREAD

**Issue by renzilin** [liyu95/DeepSimulator#41]
Hey,
I was using your deepsimulator to generate some fast5 files with deep_simulator.sh
Here is the cmd line `$DS/deep_simulator.sh -i fasta/th01_editted/th01_0.fasta  -n 200 -S 110 -B 2 -M 0 -o simu_fast5/th01 -H $DS`
The DS is the full path where the software located. I used -H to make sure the minimap2 work.

However, there is a bug.
![image](https://user-images.githubusercontent.com/17135904/85784601-6fac6300-b6f6-11ea-8c99-c5aedfd8c1e3.png)
I though it was because the sh script can't find the minimap2, but after I added the minimap path by -H, it still shows the error. 

Best,
Zilin

**Comment by renzilin** [comment]
Besides that. If there are several reads in the template fasta file, will the DeepSimulator generate NUM_OF_TEMPLATES * NUM_OF_SIMULATED_READ reads ? Thank you!

**Comment by liyu95** [comment]
Hi, thank you very much for your interest!
Could you please check whether you get the same bug on the example we provided?

**Comment by renzilin** [comment]
Dear Yu,
Thanks for your help.
I found the template fasta sequence I provide may cause the both problems I
put on github issues.
The template is too short (201 bp) to introduce the noise into the signal
if I use the default signal std and event std.

Thank you again.

Best,
Zilin
