### ISSUE TITLE
Issue about same repeated simulates

### ISSUE THREAD

**Issue by renzilin** [liyu95/DeepSimulator#42]
Hey,
I was trying to simulate 200 signals from the only one reference, I found that the generated signals are all the same. Even I used different seed and generated one by one, the simulates are all the same.
Is there anythin parameter I didn't use? Please provide some advice.

Thank you!

Best,
Zilin

**Comment by liyu95** [comment]
Hi, thank you very much for your interest!

Here is the link to the common parameters you can use: https://github.com/liyu95/DeepSimulator/wiki/Parameters-of-DS1.5
You can also find the parameters with ```./deep_simulator.sh```.

With different seeds, I can get different reads. You can also try with different noise levels, as shown in the paper.
